---
- ansible.builtin.include_tasks: modern.yaml
  when: modern_profile | bool
- name: Validate legacy architecture
  ansible.builtin.assert:
    that: server_arch == 'amd64'
    fail_msg: "Legacy profiles only support amd64; use v1.36 for arm64."
  when: not modern_profile | bool
- ansible.builtin.include_tasks: legacy.yaml
  when: not modern_profile | bool
